name: Render Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build web Docker image
        run: docker build -f deploy/Dockerfile.web -t michal-web .

  build-agent:
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build agent Docker image
        run: docker build -f deploy/Dockerfile.agent -t michal-agent .
